blank_issues_enabled: false
contact_links:
  - name: Contact Support
    url: https://www.seabird.com/support
    about: For questions regarding other Sea-Bird software or hardware, or if you require more information about deployment techniques and troubleshooting
